apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: sha2121/nodeapp:1
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_HOST
          value: mongodb
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PASSWORD
          value: strong
        - name: KAFKA_BROKER
          value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: my-node-app
spec:
  type: NodePort
  selector:
    app: my-node-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080